In [ ]:
# Phase 4: Epidemiological Indicators

## Objective
This phase focuses on calculating key public health indicators
to better understand COVID-19 severity and transmission patterns.

Indicators calculated:
- Case Fatality Rate (CFR)
- Mortality Rate
- Infection Rate
- Growth Rate
- 7-Day Moving Average

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# ==========================================
# 2. Load Dataset
# ==========================================

df = pd.read_csv(r"C:\Profile\Data\raw_data.csv")

In [3]:
df.head()

,Date_reported,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths,Case Fatality Rate
0,1/5/2020,Armenia,EURO,NaN,0,NaN,0,NaN
1,1/12/2020,Armenia,EURO,NaN,0,NaN,0,NaN
2,1/19/2020,Armenia,EURO,NaN,0,NaN,0,NaN
3,1/26/2020,Armenia,EURO,NaN,0,NaN,0,NaN
4,2/2/2020,Armenia,EURO,NaN,0,NaN,0,NaN

In [ ]:
## 1. Case Fatality Rate (CFR)

Case Fatality Rate represents the proportion of confirmed COVID-19 cases that resulted in death.

Formula:

CFR = (Cumulative_deaths / Cumulative_cases) × 100

In [4]:
df['CFR'] = (
    df['Cumulative_deaths'] /
    df['Cumulative_cases']
) * 100

In [5]:
df[['Country', 'Date_reported', 'Cumulative_cases', 'Cumulative_deaths',]].head()

   Country Date_reported  Cumulative_cases  Cumulative_deaths
0  Armenia      1/5/2020                 0                  0
1  Armenia     1/12/2020                 0                  0
2  Armenia     1/19/2020                 0                  0
3  Armenia     1/26/2020                 0                  0
4  Armenia      2/2/2020                 0                  0

In [ ]:
## 2. Mortality Rate

Mortality Rate measures the number of deaths caused by COVID-19 
relative to the total population.

Formula:

Mortality Rate = (Total Deaths / Population) × 100,000

This indicator shows the impact of COVID-19 on the entire population.

In [6]:
df.columns.tolist()

['Date_reported',
 'Country',
 'WHO_region',
 'New_cases',
 'Cumulative_cases',
 'New_deaths',
 'Cumulative_deaths',
 'Case Fatality Rate',
 'CFR']

In [ ]:
## 3. Infection Rate

Infection Rate measures the proportion of the population that was infected 
with COVID-19.

Formula:

Infection Rate = (Cumulative_cases / Population) × 100

This indicator helps estimate the spread of the disease within a population.

In [ ]:
## Note

Infection Rate was not calculated because population data 
is not available in the current dataset.

In [ ]:
## 4. Growth Rate

Growth Rate measures the percentage change in new COVID-19 cases 
compared with the previous day.

Formula:

Growth Rate = ((Current Cases - Previous Cases) / Previous Cases) × 100

This indicator helps identify periods of rapid increase or decrease 
in disease transmission.